"""phase 0

Revision ID: 0a083f98d617
Revises: 
Create Date: 2026-09-03 18:23:30.832687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0a083f98d617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.String(length=50), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('agent_insights',
    sa.Column('insight_id', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('agents_involved', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(length=1000), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('facility_reports',
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('s3_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('budget_transactions',
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('budget_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.budget_id'], ),
    sa.ForeignKeyConstraint(['cost_id'], ['cost_records.cost_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('roi_analysis',
    sa.Column('roi_id', sa.String(length=50), nullable=False),
    sa.Column('opportunity_id', sa.String(length=50), nullable=False),
    sa.Column('investment_amount', sa.Float(), nullable=True),
    sa.Column('annual_saving', sa.Float(), nullable=True),
    sa.Column('roi_percentage', sa.Float(), nullable=True),
    sa.Column('payback_period_months', sa.Float(), nullable=True),
    sa.Column('net_benefit_5yr', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['optimization_opportunities.opportunity_id'], ),
    sa.PrimaryKeyConstraint('roi_id')
    )
    op.drop_table('intelligence_events')
    op.drop_column('optimization_opportunities', 'payback_period')
    op.drop_column('optimization_opportunities', 'ROI')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimization_opportunities', sa.Column('ROI', sa.FLOAT(), nullable=True))
    op.add_column('optimization_opportunities', sa.Column('payback_period', sa.FLOAT(), nullable=True))
    op.create_table('intelligence_events',
    sa.Column('event_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('facility_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('agent', sa.VARCHAR(length=50), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.drop_table('roi_analysis')
    op.drop_table('budget_transactions')
    op.drop_table('facility_reports')
    op.drop_table('agent_insights')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
