import React, { useEffect, useState } from 'react';
import { useFacility } from '../context/FacilityContext';
import { fetchRecommendations } from '../services/api';
import { GlassCard } from '../components/common/GlassCard';
import { 
  Lightbulb, 
  DollarSign, 
  Zap, 
  ArrowRight, 
  CheckCircle2, 
  Sliders, 
  Building,
  RefreshCw
} from 'lucide-react';

export const RecommendationsPage = () => {
  const { selectedFacilityId, refreshTrigger } = useFacility();
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [implementedMap, setImplementedMap] = useState({});

  useEffect(() => {
    loadRecommendations();
  }, [selectedFacilityId, refreshTrigger]);

  const loadRecommendations = async () => {
    setLoading(true);
    try {
      const data = await fetchRecommendations(selectedFacilityId);
      setRecommendations(data);
    } catch (err) {
      console.error("Failed to load recommendations:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleImplement = (recId) => {
    setImplementedMap(prev => ({ ...prev, [recId]: true }));
  };

  const totalUsdSavings = recommendations.reduce((acc, r) => acc + (r.estimated_savings_usd || 0), 0);
  const totalKwhSavings = recommendations.reduce((acc, r) => acc + (r.estimated_savings_kwh || 0), 0);

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <Lightbulb className="w-6 h-6 text-amber-400" />
            <span>AI Energy Savings & Optimization Engine</span>
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Automated recommendations generated by analyzing facility baseline variations and operational anomalies.
          </p>
        </div>

        <button
          onClick={loadRecommendations}
          className="flex items-center gap-2 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs border border-slate-700 transition-colors"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          <span>Re-analyze Facility</span>
        </button>
      </div>

      {/* Aggregate Potential Savings Summary Banner */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="glass-panel p-5 border border-emerald-500/30 bg-gradient-to-r from-emerald-950/40 via-slate-900 to-slate-900 flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Total Potential Cost Savings</p>
            <p className="text-3xl font-bold font-mono text-emerald-300 mt-1">
              ${totalUsdSavings.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} <span className="text-xs text-slate-400 font-sans">/ month</span>
            </p>
            <p className="text-[11px] text-slate-400 mt-1">Based on standard $0.14/kWh commercial electricity rate</p>
          </div>
          <div className="p-4 rounded-2xl bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
            <DollarSign className="w-8 h-8" />
          </div>
        </div>

        <div className="glass-panel p-5 border border-cyan-500/30 bg-gradient-to-r from-cyan-950/40 via-slate-900 to-slate-900 flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Total Energy Reduction</p>
            <p className="text-3xl font-bold font-mono text-cyan-300 mt-1">
              {totalKwhSavings.toLocaleString()} <span className="text-xs text-slate-400 font-sans">kWh / month</span>
            </p>
            <p className="text-[11px] text-slate-400 mt-1">Reduces ~{(totalKwhSavings * 0.00082).toFixed(1)} Tons CO₂e monthly</p>
          </div>
          <div className="p-4 rounded-2xl bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
            <Zap className="w-8 h-8" />
          </div>
        </div>
      </div>

      {/* Recommendations Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {recommendations.map((rec) => {
          const isHigh = rec.priority === 'High';
          const isMedium = rec.priority === 'Medium';
          const isDone = implementedMap[rec.id];

          return (
            <div 
              key={rec.id}
              className={`glass-panel p-6 relative flex flex-col justify-between border transition-all ${
                isDone 
                  ? 'border-emerald-500/40 bg-emerald-950/10 opacity-75' 
                  : isHigh 
                  ? 'border-cyan-500/40 hover:border-cyan-400' 
                  : 'border-slate-800 hover:border-slate-700'
              }`}
            >
              <div>
                {/* Header */}
                <div className="flex items-center justify-between gap-3 mb-3">
                  <div className="flex items-center gap-2">
                    <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold border uppercase tracking-wider ${
                      isHigh ? 'bg-rose-500/20 text-rose-300 border-rose-500/40' :
                      isMedium ? 'bg-amber-500/20 text-amber-300 border-amber-500/40' :
                      'bg-slate-800 text-slate-300 border-slate-700'
                    }`}>
                      {rec.priority} Priority
                    </span>
                    <span className="px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-400 border border-cyan-800 text-[10px] font-mono">
                      {rec.category}
                    </span>
                  </div>

                  <span className="text-xs text-slate-400 flex items-center gap-1 font-medium">
                    <Building className="w-3.5 h-3.5 text-cyan-400" />
                    {rec.facility_name}
                  </span>
                </div>

                {/* Title */}
                <h3 className="text-base font-bold text-slate-100 mb-2">{rec.title}</h3>

                {/* Savings Pill */}
                <div className="flex items-center gap-4 my-3 p-3 rounded-xl bg-slate-900/80 border border-slate-800">
                  <div>
                    <span className="text-[10px] uppercase text-slate-500 font-semibold block">Est. Cost Savings</span>
                    <span className="text-lg font-bold font-mono text-emerald-400">+${rec.estimated_savings_usd}/mo</span>
                  </div>
                  <div className="h-8 w-px bg-slate-800"></div>
                  <div>
                    <span className="text-[10px] uppercase text-slate-500 font-semibold block">Est. Energy Savings</span>
                    <span className="text-lg font-bold font-mono text-cyan-400">{rec.estimated_savings_kwh} kWh</span>
                  </div>
                </div>

                {/* Reason */}
                <div className="space-y-2 text-xs">
                  <div>
                    <span className="font-semibold text-slate-300 text-[11px] uppercase tracking-wider block">Root Cause / Reason:</span>
                    <p className="text-slate-400 leading-relaxed mt-0.5">{rec.reason}</p>
                  </div>
                  
                  {/* Suggested Action */}
                  <div className="pt-2">
                    <span className="font-semibold text-slate-200 text-[11px] uppercase tracking-wider block">Suggested Action Plan:</span>
                    <p className="text-slate-300 leading-relaxed mt-0.5 p-2.5 rounded-lg bg-slate-950/60 border border-slate-800">
                      {rec.suggested_action}
                    </p>
                  </div>
                </div>

              </div>

              {/* Action Button */}
              <div className="mt-6 pt-4 border-t border-slate-800/80 flex items-center justify-between">
                <span className="text-[10px] font-mono text-slate-500">ID: {rec.id}</span>

                {isDone ? (
                  <span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-400 bg-emerald-500/10 px-3 py-1.5 rounded-xl border border-emerald-500/30">
                    <CheckCircle2 className="w-4 h-4" /> Action Dispatched
                  </span>
                ) : (
                  <button
                    onClick={() => handleImplement(rec.id)}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 shadow-md shadow-cyan-500/20 transition-all cursor-pointer"
                  >
                    <span>Implement Action Plan</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>

            </div>
          );
        })}
      </div>

    </div>
  );
};
